### PR TITLE
Support analysis over multiple systems

### PR DESCRIPTION
**Pull request by zdou0830**
Example usage:

`compare-mt ./example/ted.ref.eng example/ted.sys2.eng example/ted.sys1.eng example/ted.sys2.eng --compare_scores score_type=bleu,bootstrap=1000,compare_directions="0-1;1-2"`

I will resolve the conflicts.

### CODE REVIEW

**Comment by neubig** [comment]
Thanks! Basically LGTM. Could you resolve the conflicts and we can merge?

**Comment by zdou0830** [comment]
Thank you! I am working on that!

**Comment by zdou0830** [comment]
Conflicts resolved! Please take another look.

**Comment by neubig** [comment]
Awesome, thanks!

**Pull request merged**
