### PR TITLE
Added ability to bucket sentences by external label

### PR DESCRIPTION
**Pull request by zdou0830**
#89 .

Sample usage:
`compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --compare_sentence_buckets 'bucket_type=label,out_labels=example/ted.sys1.eng.senttag;example/ted.sys2.eng.senttag,label_set=0+10+20+30+40+50+60+70+80+90+100,statistic_type=score,score_measure=bleu'`

`compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --compare_sentence_buckets 'bucket_type=numlabel,out_labels=example/ted.sys1.eng.senttag;example/ted.sys2.eng.senttag,bucket_cutoffs=0:10:20:30:40:50:60:70:80:90:100,statistic_type=score,score_measure=bleu'`

### CODE REVIEW

**Comment by neubig** [comment]
Thanks! Could you add the example here to the README as well?

**Comment by zdou0830** [comment]
Thank you! Here I just label each sentence with its length. Is this suitable to be put in README or is there any more informative labelling method?

**Comment by neubig** [comment]
Yeah, that's fine for now. Other things we could think of would be something like per-word language model probability (for `numlabel`) or whether the reference sentence contains a question word, which would tell you about how well something can do on questions (for `label`).

**Comment by zdou0830** [comment]
Thank you! I've updated the README!

**Comment by neubig** [comment]
Thanks a lot!

Also one github protip:
If you write "Fixes #89" (instead of just "#89"), then the issue will be automatically closed when the PR is merged, which can be convenient.

**Pull request merged**
