### PR TITLE
Make it a python package

### PR DESCRIPTION
**Pull request by pmichel31415**
This makes compare-mt a python module.

Main changes:
- all source files are moved to the `compare_mt` folder
- relative imports
- need to install with `python setup.py install`
- `python compare_mt.py` is now `compare-mt` (same for compare_ll)
- Modified the README to reflect those changes
- All example commands in the README are now run by travis CI to check for deprecation

After this PR is merged I will work setting up the pypi repo and automatic deployment so people can pip install compare-mt.

EDIT: cf #9

### CODE REVIEW

**Comment by pmichel31415** [comment]
OK good thing I added integration tests it seems like the bootstrap resampling example in the readme leads to a bug:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/compare-mt", line 11, in <module>
    load_entry_point('compare-mt==0.1', 'console_scripts', 'compare-mt')()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/compare_mt-0.1-py3.6.egg/compare_mt/compare_mt.py", line 346, in main
    report = generate_score_report(ref, out1, out2, **kargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/compare_mt-0.1-py3.6.egg/compare_mt/compare_mt.py", line 37, in generate_score_report
    wins, sys1_stats, sys2_stats = sign_utils.eval_with_paired_bootstrap(ref, out1, out2, score_type=score_type, num_samples=int(bootstrap))
TypeError: eval_with_paired_bootstrap() got an unexpected keyword argument 'score_type'
```

**Comment by zdou0830** [comment]
Oops. I think this bug was introduced during merging.

**Comment by pmichel31415** [comment]
That was my suspicion as well. Anyway it was a quick fix and hopefully with the added integration tests this kind of bug will be easier to detect

**Comment by neubig** [comment]
Thanks!

**Pull request merged**
