### PR TITLE
Ability to specify p-value threshold

### PR DESCRIPTION
**Pull request by zdou0830**
#90

### CODE REVIEW

**Comment by pmichel31415** [comment]
Nice! Can you add a command line argument for this as well? I think it'd be ready to merge after that.

**Comment by neubig** [comment]
It should already be possible by adding an option to compare_scores

**Comment by zdou0830** [comment]
Right. Should I change the sample usage in README to
`compare-mt example/ted.ref.eng example/ted.sys1.eng example/ted.sys2.eng --compare_scores score_type=bleu,bootstrap=1000,prob_thresh=0.05`?

**Comment by pmichel31415** [comment]
I think that would be a good idea. It would be nice to have a good documentation of what options are available (without looking at the code) but that's a separate issue

**Comment by zdou0830** [comment]
Thank you! Done.

**Pull request merged**
