### PR TITLE
Detokenized BLEU as new scorer type

### PR DESCRIPTION
**Pull request by bricksdont**
This PR adds detokenized BLEU as a further scorer type. Scores are based on sacrebleu (additional dependency, but it is a lightweight Python library).

Some previous discussion about this PR:

https://github.com/neubig/util-scripts/pull/7

Some details:
- Also added some detokenized test data, for `test_scorers.py`
- Additionally, I fixed some warnings I got from pytest (pytest==4.4.1, Python 3.7.2) - please let me know if that is acceptable for you.

Kind regards
Mathias

### CODE REVIEW

**Comment by bricksdont** [comment]
Hi, are you interested in this PR?

**Comment by neubig** [comment]
Yes, sorry! It's been a busy few weeks but I'll try to review it this week

**Comment by zdou0830** [comment]
Hi @bricksdont, thanks! Are you interested in implementing "cache_stats" and "score_cached_corpus" for SacreBLEU so that we can perform significance tests efficiently?

**Comment by neubig** [comment]
@bricksdont Thanks! I just reviewed it now. Instead of DetokBleuScorer, could we maybe just call it SacreBleuScorer? SacreBleu is a specific type of detokenization, etc., so I think it'd be better to be more specific in this case. Other than that, looks good.

@zdou0830, I don't think implementing cache_stats would be easy here, as sacrebleu is an external program. If you think it's possible maybe we can do it at a later point in a different PR.

**Comment by zdou0830** [comment]
I think it might be possible because sacreBLEU has functions like "get_corpus_statistics", but I haven't looked at the code in detail yet. I could try to do that in a different PR.

**Comment by bricksdont** [comment]
@neubig Sure, I can change the scorer name. However, sacrebleu tokenization is equivalent to `mteval-v13a`, so it's quite standard. Overall, output is equivalent to `multibleu-detok.perl`.

@zdou0830  About cached statistics: I am not sure this is worth the trouble since computing BLEU is fast / instantaneous for test sets of common sizes such as a few thousand lines.

**Comment by bricksdont** [comment]
I looked into `get_corpus_statistics` from sacrebleu, to potentially use it for cached scoring in compare-mt. Findings:

In compare-mt, what is cached are precision terms and lengths:
- `cache_stats` is a list of tuples `[t1, t2, t3...]`, there are as many tuples as there are sentences in ref/hypothesis
- individual tuples are `(ref length, hyp length, precision)`
- precision is a list uf tuples `[p1, p2, p3 ...]`, there are as many as 1 to max ngram order
- individual precision tuples are `(num, denom)`, numerator and denominator to compute precision of a certain ngram order

In sacrebleu,
- `get_corpus_statistics` uses `get_sentence_statistics`, both are not used at all for calculating BLEU, but ChrF
- for ChrF, the functions return character ngram statistics

**Comment by bricksdont** [comment]
(The CI build is failing, but the error seems unrelated to my changes)

**Comment by zdou0830** [comment]
I implemented cache_stats and pushed the code to a new branch [https://github.com/neulab/compare-mt/tree/sacrebleu](url). I would create a new PR once this branch is merged.

**Comment by pmichel31415** [comment]
Try rebasing, the tests should pass now (just to make sure)

**Comment by bricksdont** [comment]
I rebased my branch onto neulab:master, which clutters commit history a bit. Hope it's fine now.

**Pull request merged**
